"""Initial migration.

Revision ID: 5f00bd174aa0
Revises: 
Create Date: 2024-06-05 03:17:46.290095

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5f00bd174aa0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('price_excl_tax', sa.Float(), nullable=False),
    sa.Column('price_incl_tax', sa.Float(), nullable=False),
    sa.Column('tax', sa.Float(), nullable=False),
    sa.Column('availability', sa.Integer(), nullable=False),
    sa.Column('num_reviews', sa.Integer(), nullable=False),
    sa.Column('stars', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('product_type', sa.String(length=255), nullable=False),
    sa.Column('upc', sa.String(length=255), nullable=False),
    sa.Column('url', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('books')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('books',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('url', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('title', mysql.TEXT(), nullable=False),
    sa.Column('upc', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('product_type', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('price_excl_tax', mysql.FLOAT(), nullable=True),
    sa.Column('price_incl_tax', mysql.FLOAT(), nullable=True),
    sa.Column('tax', mysql.FLOAT(), nullable=True),
    sa.Column('price', mysql.FLOAT(), nullable=False),
    sa.Column('availability', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('num_reviews', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('stars', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('category', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('description', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('book')
    # ### end Alembic commands ###
